import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/store";
import { Toaster } from "sonner";
import { Tektur } from "next/font/google";


const tektur = Tektur({
  variable: "--font-tektur",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "TODO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={`${tektur.className} `}
      >
        <ReduxProvider>{children}</ReduxProvider>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
